from PIL import Image
from mss import mss
import torch
import re

REGION = {
    "left": 2250,
    "top": 400,
    "width": 150,
    "height": 50,
}

##Take a screen shot of the desired region for inferencing. Also saves a png file for debugging
def capture_region():
    with mss() as sct:
        shot = sct.grab(REGION)
        img = Image.frombytes("RGB", shot.size, shot.rgb)
        img.save("screenshot.png")
    return img

#Prompt for qwen to run inference on the screenshot
def read_coordinates_from_screen(model, processor, device):
    image = capture_region()

    conversation = [
        {
            "role": "user",
            "content": [
                {"type": "image"},
                {
                    "type": "text",
                    "text": (
                        "Read the coordinates exactly as shown in the image. "
                        "The text is expected to look like X:51 Y:-697. "
                        "Return only the coordinate text. "
                        "Do not return JSON. "
                        "Do not explain anything."
                    ),
                },
            ],
        }
    ]

    ##Tell the model to accept the prompt and generate a response.
    text_prompt = processor.apply_chat_template(
        conversation,
        tokenize=False,
        add_generation_prompt=True,
    )

    ##Pepare the text and image for the model to use. Add padding to the input if it is needed and then convert everything into PyTorch tensors
    inputs = processor(
        text=[text_prompt],
        images=[image],
        padding=True,
        return_tensors="pt",
    )
    ##Takes the inputs image and promnpts and moves it to the gpu it is being run on
    inputs = {k: v.to(device) for k, v in inputs.items()}

    ## Runs the model to generate a response, disable training so only inference to save memory, 32 is the max number of output tokens, 
    ## input is the prepared prompt and image, do_sample =False helps reduce randomness and gives same output everytime, output_ids is 
    ## the tokens generated by the model.
    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=32,
            do_sample=False,
        )

    ## Clean up the response. Remove prompt and only return readable text from the generated portion of the response
    coordinates = processor.batch_decode(
        output_ids[:, inputs["input_ids"].shape[1]:],
        skip_special_tokens=True,
        clean_up_tokenization_spaces=True,
    )[0].strip()

    
    ##Isolate the numeric portion of the coordinates
    match = re.search(r"X:\s*(-?\d+)\s*Y:\s*(-?\d+)", coordinates)

    ##Assign numeric string to string variable to keep precision 
    if match:
        x_coord = match.group(1)
        y_coord = match.group(2)
    else:
        x_coord = ""
        y_coord = ""

    ##return numeric strings for coordinates
    return x_coord, y_coord